In [15]:
import pandas as pd
import numpy as np
import re
import os
from os.path import dirname
import requests
from bs4 import BeautifulSoup
import pickle
from random import randint
from time import sleep

# 1

In [1]:
data_path = os.path.join(dirname(dirname(os.getcwd())),'data')

imdb_data_path = os.path.join(data_path,'imdb')
#imdb_n_basics = pd.read_csv(imdb_data_path+'/name.basics.tsv/data.tsv',sep='\t',index_col=0)
imdb_t_akas = pd.read_csv(imdb_data_path+'/title.akas.tsv/data.tsv',sep='\t',index_col=0)
imdb_t_basic = pd.read_csv(imdb_data_path+'/title.basics.tsv/data.tsv',sep='\t',index_col=0)
#imdb_t_princ = pd.read_csv(imdb_data_path+'/title.principals.tsv/data.tsv',sep='\t',index_col=0)
imdb_t_rating = pd.read_csv(imdb_data_path+'/title.ratings.tsv/data.tsv',sep='\t',index_col=0)

NameError: name 'os' is not defined

In [4]:
#imdb_t_basic.describe()

In [5]:
#imdb_t_basic['startYear'].replace('\\N',None)

In [6]:
#imdb_t_basic.head(1)

In [7]:
#imdb_t_basic['startYear'] = imdb_t_basic['startYear'].astype(int)

In [3]:
save_ind = []
for i in imdb_t_basic.index:
    year = imdb_t_basic.loc[i,'startYear']
    if year[0:2]=='18' or year[0:3] in ['190','191','192','193','194','195','196','197','198']:
        save_ind.append(i)

In [4]:
len(imdb_t_rating)

1326238

In [5]:
imdb_t_basic.drop(index=save_ind,inplace=True)
len(imdb_t_basic)

8652426

In [11]:
# imdb = imdb_t_basic.join(imdb_t_rating,how='inner')
# len(imdb)

1065511

In [179]:
imdb = pd.merge(imdb_t_basic, imdb_t_rating, left_index=True, right_index=True)
len(imdb)

1065511

In [12]:
imdb.head()

,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,averageRating,numVotes
tconst,,,,,,,,,,
tt0000929,short,Klebolin klebt alles,Klebolin klebt alles,0,1990,\N,\N,"Comedy,Short",5.3,46
tt0013274,movie,Istoriya grazhdanskoy voyny,Istoriya grazhdanskoy voyny,0,2021,\N,94,Documentary,6.8,56
tt0015414,movie,La tierra de los toros,La tierra de los toros,0,2000,\N,60,\N,5.3,16
tt0015724,movie,Dama de noche,Dama de noche,0,1993,\N,102,"Drama,Mystery,Romance",6.1,26
tt0034841,short,Hen Hop,Hen Hop,0,1994,\N,4,"Animation,Short",6.2,278

In [180]:
save_ind = []
for i in imdb.index:
    year = imdb.loc[i,'startYear']
    rating = imdb.loc[i,'averageRating']
    if year[0:2]=='19' and rating<7.9:
        save_ind.append(i)

imdb.drop(index=save_ind,inplace=True)
len(imdb)

967429

In [15]:
imdb.head()

,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,averageRating,numVotes
tconst,,,,,,,,,,
tt0013274,movie,Istoriya grazhdanskoy voyny,Istoriya grazhdanskoy voyny,0,2021,\N,94,Documentary,6.8,56
tt0015414,movie,La tierra de los toros,La tierra de los toros,0,2000,\N,60,\N,5.3,16
tt0035423,movie,Kate & Leopold,Kate & Leopold,0,2001,\N,118,"Comedy,Fantasy,Romance",6.4,87032
tt0040241,short,Color Rhapsodie,Color Rhapsodie,0,2021,\N,6,Short,7.7,16
tt0043139,movie,Life of a Beijing Policeman,Wo zhe yi bei zi,0,2013,\N,120,"Drama,History",7.2,190

In [181]:
save_ind = []
for i in imdb.index:
    year = imdb.loc[i,'startYear']
    rating = imdb.loc[i,'averageRating']
    if rating<6.5:
        save_ind.append(i)

imdb.drop(index=save_ind,inplace=True)
len(imdb)

710175

In [182]:
imdb_en = imdb_t_akas[imdb_t_akas['language']=='en']
imdb_en.head(10)

,ordering,title,region,language,types,attributes,isOriginalTitle
titleId,,,,,,,
tt0000005,4,Blacksmith Scene,CA,en,imdbDisplay,\N,0
tt0000010,6,La sortie de l'usine Lumière à Lyon,CA,en,imdbDisplay,\N,0
tt0000012,22,The Arrival of a Train,XWW,en,imdbDisplay,\N,0
tt0000012,24,L'arrivée d'un train à La Ciotat,CA,en,imdbDisplay,\N,0
tt0000012,27,The Arrival of a Train,XEU,en,imdbDisplay,\N,0
tt0000012,9,The Arrival of a Train at La Ciotat,XWW,en,alternative,\N,0
tt0000013,11,The Photographical Congress Arrives in Lyon,XWW,en,imdbDisplay,\N,0
tt0000016,1,Boat Leaving the Port,XWW,en,imdbDisplay,\N,0
tt0000023,11,A Dip in the Sea,XWW,en,alternative,\N,0
tt0000023,4,The Sea,XWW,en,imdbDisplay,\N,0

In [183]:
len(imdb_en)

470831

In [184]:
IMDB_EN = pd.merge(imdb, imdb_en, left_index=True, right_index=True)
len(IMDB_EN)

149698

In [185]:
IMDB_EN

,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,averageRating,numVotes,ordering,title,region,language,types,attributes,isOriginalTitle
tconst,,,,,,,,,,,,,,,,,
tt0013274,movie,Istoriya grazhdanskoy voyny,Istoriya grazhdanskoy voyny,0,2021,\N,94,Documentary,6.8,56,7,The History of the Civil War,XWW,en,\N,informal literal English title,0
tt0043139,movie,Life of a Beijing Policeman,Wo zhe yi bei zi,0,2013,\N,120,"Drama,History",7.2,190,5,Life of a Beijing Policeman,XWW,en,imdbDisplay,\N,0
tt0069049,movie,The Other Side of the Wind,The Other Side of the Wind,0,2018,\N,122,Drama,6.7,7735,18,The Other Side of the Wind,CA,en,imdbDisplay,\N,0
tt0088473,tvSeries,Adventures in Wonderland,Adventures in Wonderland,0,1992,1994,30,"Adventure,Comedy,Family",7.9,790,1,Disney's Adventures in Wonderland,CA,en,imdbDisplay,\N,0
tt0092382,tvSeries,Mother Goose Stories,Mother Goose Stories,0,1990,2000,7,"Family,Fantasy",8.4,78,4,Mother Goose Stories,IN,en,imdbDisplay,\N,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
tt9915686,tvSeries,The Khatra Show,Khatra Khatra Khatra,0,2019,\N,\N,"Comedy,Reality-TV",6.7,274,4,Khatra Khatra Khatra,IN,en,imdbDisplay,\N,0
tt9915822,tvSeries,Ichhapyaari Naagin,Ichhapyaari Naagin,0,2016,2017,20,Fantasy,8.0,62,2,Ichhapyaari Naagin,IN,en,imdbDisplay,\N,0
tt9916170,movie,The Rehearsal,O Ensaio,0,2019,\N,51,Drama,7.0,7,2,The Rehearsal,XWW,en,imdbDisplay,\N,0
tt9916216,tvSeries,Kalyanam Mudhal Kadhal Varai,Kalyanam Mudhal Kadhal Varai,0,2014,2017,22,Romance,8.5,12,3,Kalyanam Mudhal Kadhal Varai,SG,en,imdbDisplay,\N,0
tt9916216,tvSeries,Kalyanam Mudhal Kadhal Varai,Kalyanam Mudhal Kadhal Varai,0,2014,2017,22,Romance,8.5,12,4,Kalyanam Mudhal Kadhal Varai,IN,en,imdbDisplay,\N,0

In [186]:
IMDB_EN.reset_index(inplace=True)

In [187]:
import pickle

dffile = open('imdb_1l','ab')
pickle.dump(IMDB_EN,dffile)
dffile.close()

# Start Here

In [85]:
# dffile = open('imdb_1l','rb')
# IMDB_EN = pickle.load(dffile)
# dffile.close()

In [188]:
IMDB_EN.head()

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,averageRating,numVotes,ordering,title,region,language,types,attributes,isOriginalTitle
0,tt0013274,movie,Istoriya grazhdanskoy voyny,Istoriya grazhdanskoy voyny,0,2021,\N,94,Documentary,6.8,56,7,The History of the Civil War,XWW,en,\N,informal literal English title,0
1,tt0043139,movie,Life of a Beijing Policeman,Wo zhe yi bei zi,0,2013,\N,120,"Drama,History",7.2,190,5,Life of a Beijing Policeman,XWW,en,imdbDisplay,\N,0
2,tt0069049,movie,The Other Side of the Wind,The Other Side of the Wind,0,2018,\N,122,Drama,6.7,7735,18,The Other Side of the Wind,CA,en,imdbDisplay,\N,0
3,tt0088473,tvSeries,Adventures in Wonderland,Adventures in Wonderland,0,1992,1994,30,"Adventure,Comedy,Family",7.9,790,1,Disney's Adventures in Wonderland,CA,en,imdbDisplay,\N,0
4,tt0092382,tvSeries,Mother Goose Stories,Mother Goose Stories,0,1990,2000,7,"Family,Fantasy",8.4,78,4,Mother Goose Stories,IN,en,imdbDisplay,\N,0

In [189]:
IMDB_EN['region'].value_counts()

region
XWW    37531
CA     22483
IN     19747
PH     12955
SG     12734
ZA     11505
ID      7033
EG      4509
TH      3991
IL      3627
HK      2870
IE      2539
NZ      2168
JP      1948
XEU     1272
US       861
XAS      376
GB       258
CH       229
MY       226
BE       194
BD       178
PK       113
JM       107
AU        79
NG        69
DE        19
CN        16
IT         8
FR         8
ES         6
KR         6
BR         5
TW         4
AE         3
PT         2
MX         2
IR         2
HR         1
BG         1
AR         1
AF         1
ET         1
TR         1
GR         1
EC         1
RO         1
SE         1
NO         1
UA         1
XNA        1
DK         1
NL         1
Name: count, dtype: int64

In [190]:
df_dups = pd.DataFrame(IMDB_EN['tconst'].value_counts(),columns=['count'])
df_dups.head()

           count
tconst
tt9335498     46
tt5323662     29
tt2850386     29
tt0438097     26
tt1667889     26

In [ ]:
IMDB_EN[IMDB_EN['tconst'] =='tt9335498']

In [191]:
len(IMDB_EN)

149698

In [192]:
df_dups.tail()

            count
tconst
tt2215338       1
tt2215395       1
tt10873784      1
tt2215434       1
tt0013274       1

In [149]:
(IMDB_EN[IMDB_EN['tconst']=='tt22050046']['region']=='US').any()

False

In [193]:
for ind in df_dups.index:
    try:
        inUSA = (IMDB_EN[IMDB_EN['tconst']==ind]['region']=='US').any()
    except AttributeError:
        inUSA = False
        print('passed')
    if inUSA:
        index_del =  IMDB_EN[ (IMDB_EN['tconst'] == ind) & (IMDB_EN['region'] != 'US') ].index
        IMDB_EN.drop(index_del , inplace=True)
    else:
        pass # change later

len(IMDB_EN)

146415

In [212]:
df_dups = pd.DataFrame(IMDB_EN.index.value_counts(),columns=['count'])
df_dups.head()

       count
0          1
99795      1
99789      1
99790      1
99791      1

In [213]:
IMDB_usa = IMDB_EN[IMDB_EN['region']=='US']
len(IMDB_usa)

861

In [214]:
IMDB_ind = IMDB_EN[(IMDB_EN['region']=='IN') & (IMDB_EN['numVotes']>3000)]
len(IMDB_ind)

6993

In [215]:
IMDB_gb = IMDB_EN[IMDB_EN['region']=='GB']
len(IMDB_gb)

246

In [216]:
IMDB_ca = IMDB_EN[(IMDB_EN['region']=='CA') & (IMDB_EN['numVotes']>3000)]
len(IMDB_ca)

8554

In [217]:
IMDB = pd.concat([IMDB_usa,IMDB_ind,IMDB_gb,IMDB_ca])
IMDB.head()

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,averageRating,numVotes,ordering,title,region,language,types,attributes,isOriginalTitle
215,tt0102926,movie,The Silence of the Lambs,The Silence of the Lambs,0,1991,\N,118,"Crime,Drama,Thriller",8.6,1473918,50,The Silence of the Lambs,US,en,\N,\N,0
219,tt0103064,movie,Terminator 2: Judgment Day,Terminator 2: Judgment Day,0,1991,\N,137,"Action,Sci-Fi",8.6,1128166,17,Terminator 2: Judgment Day,US,en,dvd,\N,0
548,tt0107688,movie,The Nightmare Before Christmas,The Nightmare Before Christmas,0,1993,\N,76,"Animation,Family,Fantasy",7.9,352825,54,The Nightmare Before Christmas,US,en,\N,\N,0
724,tt0110357,movie,The Lion King,The Lion King,0,1994,\N,88,"Adventure,Animation,Drama",8.5,1090882,18,The Lion King 3D,US,en,\N,3-D version,0
729,tt0110357,movie,The Lion King,The Lion King,0,1994,\N,88,"Adventure,Animation,Drama",8.5,1090882,41,King of the Jungle,US,en,\N,original script title,0

In [218]:
len(IMDB)

16654

In [219]:
IMDB.index.value_counts()

215       1
38585     1
38619     1
38666     1
38697     1
         ..
103022    1
103045    1
103058    1
103060    1
149657    1
Name: count, Length: 16654, dtype: int64

In [220]:
IMDB.columns

Index(['tconst', 'titleType', 'primaryTitle', 'originalTitle', 'isAdult',
       'startYear', 'endYear', 'runtimeMinutes', 'genres', 'averageRating',
       'numVotes', 'ordering', 'title', 'region', 'language', 'types',
       'attributes', 'isOriginalTitle'],
      dtype='object')

In [242]:
IMDB.filter(items = ['tconst','titleType', 'primaryTitle', 'originalTitle', 'isAdult', 'startYear',
       'endYear', 'runtimeMinutes', 'genres', 'averageRating', 'numVotes',
        'region', 'language',
       'isOriginalTitle']).nunique()

tconst             10274
titleType             10
primaryTitle        9948
originalTitle      10034
isAdult                3
startYear             34
endYear               36
runtimeMinutes       389
genres               596
averageRating         34
numVotes            8648
region                 4
language               1
isOriginalTitle        2
dtype: int64

In [243]:
df_dups = pd.DataFrame(IMDB['tconst'].value_counts(),columns=['count'])
df_dups.head()

            count
tconst
tt11083552      3
tt5117428       3
tt0342258       3
tt3077214       3
tt1833116       3

In [232]:
len(IMDB)

16654

In [239]:
ind_lis = []
for ind in df_dups.index:
    if df_dups.loc[ind,'count']>1:

        unique_lis = list(IMDB.filter(items = ['tconst','titleType', 'primaryTitle', 'originalTitle', 'isAdult', 'startYear',
       'endYear', 'runtimeMinutes', 'genres', 'averageRating', 'numVotes',
        'region', 'language',
       'isOriginalTitle'])[IMDB['tconst']==ind].drop_duplicates(keep='first').index)
        
        dups_lis = list(IMDB.filter(items = ['tconst','titleType', 'primaryTitle', 'originalTitle', 'isAdult', 'startYear',
       'endYear', 'runtimeMinutes', 'genres', 'averageRating', 'numVotes',
        'region', 'language',
       'isOriginalTitle'])[IMDB['tconst']==ind].index)
        
        to_rem_lis = [x for x in dups_lis if x not in unique_lis]
        ind_lis.extend(to_rem_lis)
        

IMDB.drop(index=ind_lis,inplace=True)
len(IMDB)

16347

In [251]:
df_dups = pd.DataFrame(IMDB['tconst'].value_counts(),columns=['count'])
df_dups.head()

            count
tconst
tt11083552      3
tt5117428       3
tt0342258       3
tt3077214       3
tt1833116       3

In [257]:
len(IMDB)

16347

In [258]:
ind_lis = []
for ind in df_dups.index:
    if df_dups.loc[ind,'count']>1:

        unique_lis = list(IMDB.filter(items = ['tconst','titleType', 'primaryTitle', 'originalTitle', 'isAdult', 'startYear',
       'endYear', 'runtimeMinutes', 'genres', 'averageRating', 'numVotes',
         'language',
       'isOriginalTitle'])[IMDB['tconst']==ind].drop_duplicates(keep='first').index)
        
        dups_lis = list(IMDB.filter(items = ['tconst','titleType', 'primaryTitle', 'originalTitle', 'isAdult', 'startYear',
       'endYear', 'runtimeMinutes', 'genres', 'averageRating', 'numVotes',
        'language',
       'isOriginalTitle'])[IMDB['tconst']==ind].index)
        
        to_rem_lis = [x for x in dups_lis if x not in unique_lis]
        ind_lis.extend(to_rem_lis)
        

IMDB.drop(index=ind_lis,inplace=True)
len(IMDB)

10275

In [259]:
dffile2 = open('imdb_10k','ab')
pickle.dump(IMDB,dffile2)
dffile2.close()

# Start Here 2

In [208]:
# dffile2 = open('imdb_10k','rb')
# IMDB = pickle.load(dffile2)
# dffile2.close()

In [9]:
def getDescription(show_name,mode):
    show_name_l = show_name.lower()
    show_name_s = re.sub('[^a-zA-Z0-9_]',' ',show_name_l)
    show_name = re.sub(' +', ' ',show_name_s.strip())
    if mode.lower() in ['television', 'tv', 'tvshow', 'tv-show', 'tv - show', 'show', 'series']:
        try:
            url = 'https://www.rottentomatoes.com/tv/'+'-'.join(show_name.split(' '))
            agent = {"User-Agent":'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36'}
            response = requests.get(url, headers=agent)
            soup = BeautifulSoup(response.content, 'html.parser')
            soup_obj = soup.find('p',{'data-qa':'series-info-description'})
            text = soup_obj.text.strip()
        except:
            url = 'https://www.rottentomatoes.com/tv/'+'_'.join(show_name.split(' '))
            agent = {"User-Agent":'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36'}
            response = requests.get(url, headers=agent)
            soup = BeautifulSoup(response.content, 'html.parser')
            soup_obj = soup.find('p',{'data-qa':'series-info-description'})
            text = soup_obj.text.strip()     

    elif mode.lower() in ['movie', 'movies', 'film', 'films']:
        try:
            url = 'https://www.rottentomatoes.com/m/'+'-'.join(show_name.split(' '))
            agent = {"User-Agent":'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36'}
            response = requests.get(url, headers=agent)
            soup = BeautifulSoup(response.content, 'html.parser')
            soup_obj = soup.find('p',{'data-qa':'movie-info-synopsis'})
            text = soup_obj.text.strip()
        except:
            url = 'https://www.rottentomatoes.com/m/'+'_'.join(show_name.split(' '))
            agent = {"User-Agent":'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36'}
            response = requests.get(url, headers=agent)
            soup = BeautifulSoup(response.content, 'html.parser')
            soup_obj = soup.find('p',{'data-qa':'movie-info-synopsis'})
            text = soup_obj.text.strip()    
    return text

In [261]:
IMDB.head()

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,averageRating,numVotes,ordering,title,region,language,types,attributes,isOriginalTitle
215,tt0102926,movie,The Silence of the Lambs,The Silence of the Lambs,0,1991,\N,118,"Crime,Drama,Thriller",8.6,1473918,50,The Silence of the Lambs,US,en,\N,\N,0
219,tt0103064,movie,Terminator 2: Judgment Day,Terminator 2: Judgment Day,0,1991,\N,137,"Action,Sci-Fi",8.6,1128166,17,Terminator 2: Judgment Day,US,en,dvd,\N,0
548,tt0107688,movie,The Nightmare Before Christmas,The Nightmare Before Christmas,0,1993,\N,76,"Animation,Family,Fantasy",7.9,352825,54,The Nightmare Before Christmas,US,en,\N,\N,0
724,tt0110357,movie,The Lion King,The Lion King,0,1994,\N,88,"Adventure,Animation,Drama",8.5,1090882,18,The Lion King 3D,US,en,\N,3-D version,0
762,tt0110912,movie,Pulp Fiction,Pulp Fiction,0,1994,\N,154,"Crime,Drama",8.9,2118762,22,Pulp Fiction,US,en,\N,\N,0

In [275]:
IMDB['titleType'].value_counts().index

Index(['movie', 'tvSeries', 'tvMiniSeries', 'video', 'short', 'videoGame',
       'tvMovie', 'tvEpisode', 'tvSpecial', 'tvShort'],
      dtype='object', name='titleType')

In [21]:
mapping = {'movie': 'movie',
           'tvSeries':'tv',
           'tvMiniSeries':'tv',
           'video':'tv', 
           'short':'tv', 
           'videoGame':'tv',
           'tvMovie':'movie', 
           'tvEpisode':'tv', 
           'tvSpecial':'tv', 
           'tvShort':'tv'}

In [278]:
IMDB.head()

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,averageRating,numVotes,ordering,title,region,language,types,attributes,isOriginalTitle
215,tt0102926,movie,The Silence of the Lambs,The Silence of the Lambs,0,1991,\N,118,"Crime,Drama,Thriller",8.6,1473918,50,The Silence of the Lambs,US,en,\N,\N,0
219,tt0103064,movie,Terminator 2: Judgment Day,Terminator 2: Judgment Day,0,1991,\N,137,"Action,Sci-Fi",8.6,1128166,17,Terminator 2: Judgment Day,US,en,dvd,\N,0
548,tt0107688,movie,The Nightmare Before Christmas,The Nightmare Before Christmas,0,1993,\N,76,"Animation,Family,Fantasy",7.9,352825,54,The Nightmare Before Christmas,US,en,\N,\N,0
724,tt0110357,movie,The Lion King,The Lion King,0,1994,\N,88,"Adventure,Animation,Drama",8.5,1090882,18,The Lion King 3D,US,en,\N,3-D version,0
762,tt0110912,movie,Pulp Fiction,Pulp Fiction,0,1994,\N,154,"Crime,Drama",8.9,2118762,22,Pulp Fiction,US,en,\N,\N,0

In [280]:
IMDB.reset_index(drop=True,inplace=True)

In [281]:
desc_lis = []
exception_lis = []
for i in range(len(IMDB)):
    primaryTitle = IMDB.loc[i,'primaryTitle']
    mode = mapping[IMDB.loc[i,'titleType']]
    try:
        desc = getDescription(primaryTitle,mode)
    except:
        desc = None
        exception_lis.append([i,primaryTitle,IMDB.loc[i,'titleType']])
    desc_lis.append(desc)

the silence of the lambs
terminator 2 judgment day
the nightmare before christmas
the lion king
pulp fiction
the shawshank redemption
calling the ghosts a story about rape war and women
diva las vegas
titanic
corpse bride
the road to el dorado
great minds think 4 themselves
sinister sister
descent freespace the great war
gladiator
a i artificial intelligence
egypt uncovered
transformers robots in disguise
playboy s club lingerie
cyberworld
star trek enterprise
the dummy
the making of jaws
the pianist
the wedding
interstate 76
mario tennis
mario party 2
mario party 3
m caught in the act
desert lovers
snow falling on cedars spotlight on location
veggietales lyle the kindly viking
freespace 2
aqua teen hunger force
blood omen 2
bridgette s hellions
chances are
anthony bourdain s a cook s tour
debbie does iowa
kannathil muthamittal
area k
the incredibles
kirby 64 the crystal shards
alice in chains the nona tapes
coraline
millennium calendar girls
school of rock
monsters inc the video game
bluer than indigo
dead man s wish
playboy s no boys allowed
lost in new mexico the strange tale of susan hero
the terminal
playboy s playmates bustin out
collateral
sesame street elmo s magic cookbook
9 11 the road to tyranny
anniyan
kim possible the secret files
kangaroo hitchcock the making of road games
malfunkshun the andrew wood story
3 am
the island
the rolling stones four flicks 2003
veggietales the star of christmas
penthouse 25th anniversary swimsuit video
all wives party
the departed
shrek 2 the video game
veggietales an easter carol
house
age of empires
an american girl holiday
la femme nikita denise 2
mrs henderson presents
age of empires ii the age of kings
age of mythology
veggietales a snoodle s tale
d2
outside the window events in france may 1968
making white nights
final fantasy xi chains of promathia
jak iii
krystal method
veggietales sumo of the opera
it had to be you the great american songbook
two sons of francisco
brand upon the brain
hoodwinked
undisputed 2 last man standing
of ashes and atoms the story of the nasa plum brook reactor facility
horton hears a who
wonder woman
jericho s echo punk rock in the holy land
vettaiyaadu vilaiyaadu
the equalizer
inside the party
quackshot starring donald duck
vixens in uniform
an american girl adventure
12 nasty latin girls masturbating 2
khosla ka ghosla
the dark knight
alan partridge
the shark is still working the impact legacy of jaws
lost in the thinking
playboy s no boys allowed 2
veggietales minnesota cuke and the search for samson s hairbrush
r b i baseball 3
wallace and gromit the curse of the were rabbit on the set part 1
super monkey ball 3d
oz tribute the art of imagination
harold s hollywood on location then now
the call of wild
age of empires iii
awesome i shot that
silence
spongebob squarepants and friends unite
on the set the lion the witch the wardrobe
fire emblem path of radiance
sesame street what s the name of that song
inner circle line
lost destination lost
paper dolls
the boxtrolls
spider man 2
dallas buyers club
veggietales sheerluck holmes and the golden ruler
the dirt
wolves in the woods
playboy s no boys allowed 3 sweet sensations
for you i could die
legend of the end of the century conqueror
24 redemption
interstellar
we will not be held responsible
an american girl on the home front
the spy who loved me 007 in egypt
goldeneye anatomy of a stunt tank vs perrier
for your eyes only bond in greece
the world is not enough creating an icon making the teaser trailer
goldeneye anatomy of a car chase remy julienne
on her majesty s secret service george lazenby in his own words
moonraker ken adam s production films
the spy who loved me ken adam s production films
you only live twice ken adam s production films
goldeneye location scouting with peter lamont
octopussy location scouting with peter lamont
the living daylights timothy dalton on acting
veggietales larry boy and the bad apple
the last house on the left
krystal therapy
frog
jenna s provocateur
make a wish
lost secrets from the hatch 2006 v
hoop days
confrontation
pursuit
tactics
unraveling
dealings
manda bala send a bullet
overcast
doubt
glare
encounter
assault
hannah goes to hell
love
confession
precious
superman doomsday
tomb raider anniversary
spongebob and friends battle for volcano island
green zone
wager
friend
the amazing spider man
decision
execution
ally
avatar the last airbender the legend of aang
makeshift
performance
guidance
frenzy
validation
silence
revival
renewal
vellai pookal
abduction
james burke s connections
impatience
kingdom men rising
the squatchin trilogy
air jaws 2 even higher
father
transfer
justice
500 days of summer
boy culture
deti
death proof
scorn
selection
the prescription
1946 the mistranslation that shifted culture
a chance to love
vigilance
malice
new world
cadence of hyrule
going too far
the legend of zelda tears of the kingdom
i remember ashes
transalpina the road of kings
playboy s no boys allowed 4 naughty and nice
snapcube s real time fandub
one night in miami
the storied life of a j fikry
bad boy bubby being bubby
bad boy bubby christ kid you re a weirdo
saezuru tori wa habatakanai the clouds gather
go dog go
the electrical life of louis wain
aew dynamite
spongebob and friends attack of the toybots
the world is not enough the secrets of 007
the world is not enough the boat chase
goldeneye the martin chronicles directing bond segments with martin campbell s comments
killer wives
planet terror
casino royale deleted scenes
thunderball selling bonds original 1965 television commercials
live and let die conceptual art
agent elvis
the dinner parting
no time to die official title reveal of bond 25
behind the scenes with the world is not enough
love inheritance and lunch
mega man star force
cheer up mr lee
another christmas coincidence
the hammer
the giverny document
bad lieutenant port of call new orleans
nope
square one michael jackson
tron legacy
veggietales special messages
textopia
aew dark
united states of al
3 2 1 penguins
good bye my princess
iliza shlesinger unveiled
seth meyers lobby baby
the peculiar story
tom papa you re doing great
heaven s gate the cult of cults
revisioned tomb raider animated series
exhibit a denis leary vs bill hicks
the legend of vox machina
the athlete
friends the reunion
endgame
vr bangers
summer of soul or when the revolution could not be televised
treeless mountain
mccabe mrs miller way out on a limb
jackass forever
ready
talking tom and friends minis
bonnie
the mad women s ball
wojnarowicz
the flower of kim jong ii
a hero in heaven
prey
the mysterious benedict society
heineken die another day television commercial
behind the movie no time to die
007 shadows
rurouni kenshin final chapter part ii the beginning
ze frank
kia pierce brosnan james bond style television commercial
soul nomad the world eaters
faith the unholy trinity
goldeneye 007 video game television commercial
bmw z8 the world is not enough television commercial
disneynature wings of life
geico james bond parody television commercial
betrayed
r j
bad guys vile city
you knock on my door
the things we say the things we do
michelle buteau welcome to buteaupia
sesame street big bird sings
interrogation of a husband
merman academy the movie
the cabin in the woods
x men first class
super comet after the impact
revolt of master ma
detective dee heavenly gods
cult killer the story of rick rodriguez
the barbarian and the troll
ghostbusters
devil s island journey into jungle alcatraz
the windsors a royal dynasty
iron man 3
truman tennessee an intimate conversation
hyrule warriors age of calamity
fubar
the sons of sam a descent into darkness
generosity
karma s world
peerless hero
angels in exile
welcome to los feliz
hush hush sweet charlotte bruce dern remembers
among us logic
nxt takeover wargames iv
the knife of don juan
animal crossing city folk
ayan
simon
mad max fury road introduction to black chrome edition by george miller
dear paul schrader thank you for light sleeper
civil war or who do we think we are
the dinosaur game
passengers
royal tramp
inception
death of a rockstar
our father the devil
the search for frida
showing up
hamsters and flutes
better you than me
an ave maria with consequences
parking in the snail s shell
laugh already
maggie
it
the making of never say never again
forest i see you everywhere
eagles
tanzania a journey within
monster high
the pale blue eye
unnaipol oruvan
asteroid city
deadpool
origins
lockdown
the build up
mumbai diaries
hubble
passover gay
rio
wild russia
monster pets a hotel transylvania short film
t r
the legend of jack and diane
falling angel
spider man ps4 gameplay with cottrello
the scent of passion
derbez camp
llama llama llama
forward 1
i love montana
here we go again
3 months later
coming out colton
the conjuring
just for tonight
jeen yuhs a kanye trilogy
generation y
all about my sisters
olympic highlights with kevin hart snoop dogg
dee renjie s burning sky extraordinary fire
sesame street mecha builders
aew rampage
aew all out 2021
mission joy finding happiness in troubled times
the art of racing in the rain
illegal
the hitman s bodyguard deleted scenes
the hitman s bodyguard extended scenes
the hitman s bodyguard alternate scenes
at middleton
a christmas carol the video game
one piece strong world
triple frontier
booksmart
mental
bad boys for life
apples oranges lemons limes
the world s biggest family an anonymous sperm donor s legacy
goofy in how to stay at home
a star is born
the walking dead
blinkytm
sesame street being green
a ruby herring mystery
cowboys gang life 4 ever
werewolf by night
tree climbing lions
the gods 2 the dark side
the taking
an inborn desire
smile
the voice of the voiceless
the royal world premiere of no time to die
kangaroo valley
the girl with the dragon tattoo
no time to die anatomy of a scene
elemental
bond 25 cnn no time to die special
a soldier s love story
the dragon tomb
rehabilitation from the book of saw
rupaul s drag race untucked
the clone
di renjie red eyes
bill cunningham new york
the father
detective dee under the tower
paranorman
burzynski cancer is serious business
america the story of the us
missing
diary of a wimpy kid rodrick rules
super 8
the neighbor
sonic colors
masterchef usa
the legend of korra
women art revolution
hero dog 2
who the bleep did i marry
act ii purpose
act iii awakening
tales from the lumber yard the making of galaxy of terror
the condemned
memories of a lost love
silver or lead
holbrook twain an american odyssey
trouble in the heights
chica
the silent truth
gordon ramsay s ultimate christmas
pretty bad actress
taylor tomlinson look at you
my so has got depression
the blues brothers transposing the music
the blues brothers remembering john
black panther
bill russell legend
last man standing
scandal
american horror story
toy story toons hawaiian vacation
to write love on her arms
invisible empire
blade runner 2049
the highwaymen
deepwater horizon
the amazing spider man 2
a christmas detouring message
into the white
oblivion
a man among wolves
winners
love on the spectrum u s
fast furious 6
stanley ka dabba
fugitive the curious case of carlos ghosn
iron chef brazil
penguins of madagascar
no time to die designing bond
behind closed doors
my heart beats for lola volc n
mont reve short
heroes of dirt
roxy road
ford v ferrari
the immigrant
carl a
reel black love
unconditional love
aew x njpw forbidden door
still a michael j fox movie
snoopy presents to mom and dad with love
tomorrowmen
in space with markiplier part 2
southbound heist
naked sword s golden gate
400 miles to freedom
home sweet rome
toy story toons small fry
crazy horse
dark suns
it was related to me
fishing without nets
super mario 3d land
the delhi show
the hunt
queenie
passions of the heart
the talisman
pretty perfect
trainwreck woodstock 99
dancing in jaffa
matilda the musical
jo koy live from the los angeles forum
long shot
the current war director s cut
gabriel iglesias stadium fluffy
alphabet lore
sesame street imagine that
the night before christmas
iliza shlesinger hot forever
fearless heart
habana libre
the redemption of the fish
inside
maddy may s mayhem
born to fly elizabeth streb vs gravity
top ten
sesame street 123 count with me
return to the uss atlanta
the one who loves you
the real anthony fauci
guntucky
jacques cousteau rediscover the world ii
sesame street sing yourself silly
washington heights
secret history of hacking
toy story toons partysaurus rex
fast n loud
vena amoris
at all costs
jim jefferies high n dry
how to train your dragon the hidden world
1000 to 1 the cory weissman story
reality
mr rabbit
20 feet from stardom
partners in crime clint eastwood and angelina jolie
trick r treat making friends
the loneliest whale the search for 52
troop zero
saving mes aynak
the fundamentals of caring
the rack pack
the secrets of skyfall
on the art of war
dreams of darkness
extremely wicked shockingly evil and vile
brave miss world
bryce
star wars episode viii the last jedi
star wars episode ix the rise of skywalker
in god we trust
children s theater critic with alfred molina
twist of fate
eastern front
a life in dirty movies
sharp objects
bert kreischer razzle dazzle
marvel studios building a cinematic universe
the chaperone
sleeping dogs nightmare in north point
cathedrals of culture
fifi howls from happiness
two the story of roman nyro
hannah gadsby something special
once upon a time in wonderland
blue boy
beat beat beat
the old man the gun
the new york philharmonic s performance of rodgers hammerstein s carousel
the lucky one zac efron becomes a marine
money
soul
shining girls
the divine matrix
lego star wars the yoda chronicles
of mind and music
dawn of the head
almost holy
my sister
you belong to me sex race and murder in the south
comissarrio guido brunetti mysteries vendetta
tamasha
the legend of zelda breath of the wild
radioactive wolves
bravely default flying fairy
chance at romance
start anew world
the walking dead season two
raees
a monster calls
game of bones winter is cumming
finch
manhunt
sk1
farewell
the elder scrolls online
thor ragnarok
chip n dale rescue rangers
best of enemies buckley vs vidal
trapped
invisible spaces
the falconer
your inner fish
the oscars
bridge of spies
mata nui online game
the figures carved into the knife by the sap of the banana trees
drift
rogue one a star wars story
wrestlemania 31
big time adolescence
kamen rider gaim hyper battle dvd fresh orange arms is born you can also seize it the power of fresh
only the brave
do you mind
mad god part 2
colliding dreams
guardians of the galaxy vol 2
the seven deadly sins
puss in boots the last wish
miracle in the valley
4th man out
mysterious joker
flame
the lego batman movie
paradise in heart
captain marvel
avengers infinity war
avengers endgame
all downhill from here
give me liberty
cobain montage of heck
yennai arindhaal
the witch
qt8 the first eight
overwatch
you me and the apocalypse
the last black man in san francisco
shadowrun dragonfall director s cut
vixen
calm with horses
street food around the world
everything will be fine
invisible centerfolds
agents of s h i e l d double agent
kingdom of tyrants the extended minifilm version
christopher robin
someone i used to know
we ve met before
spider man into the spider verse
the oa
the keeper
sunrise
the groundskeeper
turncoats
a prayer for the lonely
mfkz
masque
the best of enemies
the goal how to version
gone
borderlands going legendary
mission impossible fallout
amazing grace
split
star wars rebels recon missions
dunkirk
throwing bombs in baghdad
get out
tom clancy s jack ryan
i ll find you
papillon
minions the rise of gru
steven universe unboxing
operation finale
f kin actors
dark city introduction by alex proyas and roger ebert
calling in the cavalry
understanding the madness
ultimate iron man
forgotten in california
zero days
deadpool 2
pillars of eternity the white march part i
apb
clemency
the shape of water
the man with the golden gun american thrill show stunt film
the living daylights the new james bond vienna press conference
bruce lee pursuit of the dragon early version
i hope
electric dreams
love sex tv news
the walking dead a new frontier
the one i lust
the oscars
she loves me
memoirs of a murderer
the professor and the madman
shooting blood simple
jay sebring cutting to the truth
my suburban stories
death proof foot spoof
light of my life
lucifer
patrick stewart narrates the planets
late night
the butterfly effect
if you re looking for trouble
raakshas
aladdin
gustavo goulart it drives me crazy
comeback
shamblin s shack
teen titans the judas contract
school of life
high strung free dance
the works and days of tayoko shiojiri in the shiotani basin
five feet apart
the butler gag reel
legacy the true story of the la lakers
mantis nest
long live brij mohan
the adventures of batman robin
otto frank father of anne
diane
the beep test
the super mario bros movie
the tales of the seven keys
the king
blue
mystery science theater 3000
everything gameplay film
idiots
glass
little heroes
us
making john adams
do no harm exposing the hippocratic hoax
vixen the movie
all anything or love
quest for the stanley cup
mad god part 3
fill in the prank
good boys
a gift for christmas
super deluxe
the adventures of priscilla queen of the desert the bus from blooperville
the last wave interview with director peter weir
national treasure kiri
informer
mata hari the naked spy
going to mars the nikki giovanni project
the knife shaking the habitual live at terminal 5
birth of a monster a star wars story
woman at war
shuttle life
ash is purest white
ghost of the mountains
the art of self defense
eli roth s history of horror
the submission of emma marx evolved
the outlaws
bloodless
luce
pr nom mathieu
brittany runs a marathon
the honeymoon stand up special
a call to spy
the dreaming man
harvey girls forever
the beguiled a shift in perspective
the beguiled a southern style
american made cruise and liman a conversation
american made flying high
american made the real barry seal
little red riding hood
the mighty ducks game changers
eye for an eye
the russian five
paddleton
penguin highway
penguins
the woman king
turning red
the fourth estate
seven short films about our marriage
honey boy
breaking bread
deerskin
the report
a river through the mountains
james cameron s story of science fiction
born to be
mosul
hesburgh
maradona blessed dream
mills creek
the hollow forest chronicles
horizon
the inventor out for blood in silicon valley
ibot
kickball team vs church ladies
romeo akbar walter
nubile films
the farewell
the drug hunter
the hitman s bodyguard dangerous women
the hitman s bodyguard the hitman vs the bodyguard
justice league vs the fatal five
call me by your name in conversation with armie hammer timoth e chalamet michael stuhlbarg and luca guadagnino
midsommar
one child nation
jersey
house arrest
a christmas coincidence
charm city kings
hit run
the journey of mr deshee
chitralahari
constantine city of demons the movie
dr death
are you there god it s me margaret
the falcon and the winter soldier
threads
pip
pacific rim the black
driveways
doctor strange in the multiverse of madness
the possession of mrs hyde
such sweet sorrow part 2
filming imax under the sea
our friend
fourteen
fear street part two 1978
fear street part three 1666
rifftrax live octaman
anne frank parallel stories
mr bean
the case book of sherlock holmes
the civil war
the fresh prince of bel air
house of cards
twin peaks
anjali
dances with wolves
edward scissorhands
goodfellas
close up
the stranger
beauty and the beast
raise the red lantern
thalapathi
are you afraid of the dark
batman the animated series
the larry sanders show
x men the animated series
aladdin
jo jeeta wohi sikandar
reservoir dogs
roja
scent of a woman
thevar magan
unforgiven
the adventures of brisco county jr
animaniacs
as time goes by
babylon 5
boy meets world
cracker
frasier
homicide life on the street
rocko s modern life
star trek deep space nine
the x files
bound by honor
carlito s way
groundhog day
in the name of the father

In [283]:
IMDB['Description'] = desc_lis

In [286]:
IMDB['Description'].isnull().sum()

4239

In [285]:
IMDB.isnull().sum() * 100 / len(IMDB)

tconst              0.000000
titleType           0.000000
primaryTitle        0.000000
originalTitle       0.000000
isAdult             0.000000
startYear           0.000000
endYear             0.000000
runtimeMinutes      0.000000
genres              0.000000
averageRating       0.000000
numVotes            0.000000
ordering            0.000000
title               0.000000
region              0.000000
language            0.000000
types               0.000000
attributes          0.000000
isOriginalTitle     0.000000
Description        41.255474
dtype: float64

In [287]:
dffile3 = open('imdb_desc1','ab')
pickle.dump(IMDB,dffile3)
dffile3.close()

# Start here 3

In [5]:
dffile3 = open('imdb_desc1','rb')
IMDB = pickle.load(dffile3)
dffile3.close()

In [288]:
#IMDB_not_null = IMDB.dropna(subset=['Description'])

In [305]:
#IMDB_not_null.tail(20)

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,averageRating,numVotes,ordering,title,region,language,types,attributes,isOriginalTitle,Description
8118,tt0257850,tvMovie,The Laramie Project,The Laramie Project,0,2002,\N,97,"Crime,Drama,History",7.1,6796,1,The Laramie Project,CA,en,imdbDisplay,\N,0,"""The Laramie Project"" is set in and around Lar..."
8120,tt0258967,movie,The Unsaid,The Unsaid,0,2001,\N,111,"Crime,Drama,Mystery",6.6,6611,1,The Unsaid,CA,en,imdbDisplay,\N,0,Emotionally distraught after his son's suicide...
8123,tt0259393,movie,Lantana,Lantana,0,2001,\N,121,"Drama,Mystery,Romance",7.2,19952,16,Lantana,CA,en,imdbDisplay,\N,0,Plagued with grief over the murder of her daug...
8124,tt0259446,movie,My Big Fat Greek Wedding,My Big Fat Greek Wedding,0,2002,\N,95,"Comedy,Drama,Romance",6.6,137488,20,My Big Fat Greek Wedding,CA,en,imdbDisplay,\N,0,Everyone in the Portokalos family worries abou...
8125,tt0259484,movie,Paid in Full,Paid in Full,0,2002,\N,97,"Action,Crime,Drama",7.0,13465,9,Paid in Full,CA,en,imdbDisplay,\N,0,"In the late 1980s, Ace (Wood Harris) is a youn..."
8126,tt0261392,movie,Jay and Silent Bob Strike Back,Jay and Silent Bob Strike Back,0,2001,\N,104,Comedy,6.8,158209,20,Jay and Silent Bob Strike Back,CA,en,imdbDisplay,\N,0,"When Jay and Silent Bob learn that a ""Bluntman..."
8127,tt0263124,movie,Brainstorm,Bicho de Sete Cabeças,0,2000,\N,74,Drama,7.7,6013,9,Brainstorm,CA,en,\N,\N,0,
8129,tt0264263,tvSeries,Jackass,Jackass,0,2000,2007,535,"Action,Comedy,Reality-TV",7.3,26720,28,Jackass,CA,en,imdbDisplay,\N,0,"You've heard it a million times before, but no..."
8130,tt0264472,movie,Changing Lanes,Changing Lanes,0,2002,\N,98,"Drama,Thriller",6.5,73226,10,Changing Lanes,CA,en,imdbDisplay,\N,0,A rush-hour fender-bender on New York City's c...
8131,tt0264616,movie,Frailty,Frailty,0,2001,\N,100,"Crime,Drama,Thriller",7.2,87389,28,Frailty,CA,en,imdbDisplay,\N,0,"Set in present day Texas, ""Frailty"" centers on..."
8132,tt0264761,movie,Kissing Jessica Stein,Kissing Jessica Stein,0,2001,\N,97,"Comedy,Drama,Romance",6.6,17196,3,Kissing Jessica Stein,CA,en,imdbDisplay,\N,0,Jessica (Jennifer Westfeldt) is at the end of ...
8136,tt0265662,movie,The Rookie,The Rookie,0,2002,\N,127,"Drama,Family,Sport",6.9,36132,5,The Rookie,CA,en,imdbDisplay,\N,0,A true story about a coach who discovers that ...
8137,tt0265930,movie,The Last Kiss,L'ultimo bacio,0,2001,\N,115,"Comedy,Drama,Romance",6.9,8684,1,The Last Kiss,CA,en,imdbDisplay,\N,0,Italian couple Giulia (Giovanna Mezzogiorno) a...
8138,tt0266425,tvMovie,Conspiracy,Conspiracy,0,2001,\N,96,"Biography,Drama,History",7.6,22989,3,Conspiracy,CA,en,imdbDisplay,\N,0,A former Marine (Val Kilmer) brings justice to...
8139,tt0269743,movie,Barking Dogs Never Bite,Flandersui gae,0,2000,\N,110,Comedy,6.9,9670,32,Flanders Dog,CA,en,imdbDisplay,\N,0,"Frustrated with loud barking, an academic (Lee..."
8140,tt0269746,movie,What Time Is It There?,Ni na bian ji dian,0,2001,\N,116,"Drama,Romance",7.3,5172,7,What Time Is It There?,CA,en,imdbDisplay,\N,0,A street vendor (Lee Kang-sheng) with a grim h...
8141,tt0270933,movie,Escaflowne: The Movie,Escaflowne,0,2000,\N,98,"Action,Adventure,Animation",6.6,3732,7,Escaflowne: The Movie,CA,en,imdbDisplay,\N,0,"""Escaflowne"" blends romance and fantasy to tel..."
8144,tt0272207,movie,Narc,Narc,0,2002,\N,105,"Crime,Drama,Mystery",7.1,42135,14,Narc,CA,en,imdbDisplay,\N,0,Tells the dark story of suspended undercover n...
8145,tt0272388,tvSeries,House of Mouse,House of Mouse,0,2001,2003,30,"Animation,Comedy,Family",7.5,4458,5,House of Mouse,CA,en,imdbDisplay,\N,0,Disney characters meet at a cartoon club.
8147,tt0274428,movie,Divine Intervention,Yadon ilaheyya,0,2002,\N,92,"Comedy,Drama,Romance",6.6,3785,9,Divine Intervention,CA,en,imdbDisplay,\N,0,A religious psychopath (Vic Clay) kills unsusp...

In [290]:
# data_path = os.path.join(dirname(dirname(os.getcwd())),'data')
# imdb_filt_path = os.path.join(data_path,'imdb_filtered')
# IMDB_not_null.to_csv(os.path.join(imdb_filt_path,'IMDB_sample1.csv'))

In [ ]:
# getDescription2('A.I. Artificial Intelligence','movie')

In [25]:
def getDescription2(show_name,mode):
    show_name_l = show_name.lower()
    show_name_s = re.sub('[^a-zA-Z0-9 ]','',show_name_l)
    show_name = re.sub(' +', ' ',show_name_s.strip())
    print(show_name)
    if mode.lower() in ['television', 'tv', 'tvshow', 'tv-show', 'tv - show', 'show', 'series']:
        try:
            url = 'https://www.rottentomatoes.com/tv/'+'-'.join(show_name.split(' '))
            agent = {"User-Agent":'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36'}
            sleep(randint(0,3))
            response = requests.get(url, headers=agent)
            soup = BeautifulSoup(response.content, 'html.parser')
            soup_obj = soup.find('p',{'data-qa':'series-info-description'})
            text = soup_obj.text.strip()
        except:
            url = 'https://www.rottentomatoes.com/tv/'+'_'.join(show_name.split(' '))
            agent = {"User-Agent":'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36'}
            sleep(randint(0,3))
            response = requests.get(url, headers=agent)
            soup = BeautifulSoup(response.content, 'html.parser')
            soup_obj = soup.find('p',{'data-qa':'series-info-description'})
            text = soup_obj.text.strip()     

    elif mode.lower() in ['movie', 'movies', 'film', 'films']:
        try:
            url = 'https://www.rottentomatoes.com/m/'+'-'.join(show_name.split(' '))
            agent = {"User-Agent":'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36'}
            sleep(randint(0,3))
            response = requests.get(url, headers=agent)
            soup = BeautifulSoup(response.content, 'html.parser')
            soup_obj = soup.find('p',{'data-qa':'movie-info-synopsis'})
            text = soup_obj.text.strip()
        except:
            url = 'https://www.rottentomatoes.com/m/'+'_'.join(show_name.split(' '))
            agent = {"User-Agent":'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36'}
            sleep(randint(0,3))
            response = requests.get(url, headers=agent)
            soup = BeautifulSoup(response.content, 'html.parser')
            soup_obj = soup.find('p',{'data-qa':'movie-info-synopsis'})
            text = soup_obj.text.strip()    
    return text

In [ ]:
#getDescription2('A.I. Artificial Intelligence','movie')

In [27]:
# Sleep a random number of seconds (between 1 and 5)
sleep(randint(0,3))

In [22]:
IMDB.head()

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,averageRating,numVotes,ordering,title,region,language,types,attributes,isOriginalTitle,Description
0,tt0102926,movie,The Silence of the Lambs,The Silence of the Lambs,0,1991,\N,118,"Crime,Drama,Thriller",8.6,1473918,50,The Silence of the Lambs,US,en,\N,\N,0,"Jodie Foster stars as Clarice Starling, a top ..."
1,tt0103064,movie,Terminator 2: Judgment Day,Terminator 2: Judgment Day,0,1991,\N,137,"Action,Sci-Fi",8.6,1128166,17,Terminator 2: Judgment Day,US,en,dvd,\N,0,"In this sequel set eleven years after ""The Ter..."
2,tt0107688,movie,The Nightmare Before Christmas,The Nightmare Before Christmas,0,1993,\N,76,"Animation,Family,Fantasy",7.9,352825,54,The Nightmare Before Christmas,US,en,\N,\N,0,None
3,tt0110357,movie,The Lion King,The Lion King,0,1994,\N,88,"Adventure,Animation,Drama",8.5,1090882,18,The Lion King 3D,US,en,\N,3-D version,0,This Disney animated feature follows the adven...
4,tt0110912,movie,Pulp Fiction,Pulp Fiction,0,1994,\N,154,"Crime,Drama",8.9,2118762,22,Pulp Fiction,US,en,\N,\N,0,Vincent Vega (John Travolta) and Jules Winnfie...

In [28]:
desc_lis2 = []
exception_lis2 = []
for i in range(len(IMDB)):
    primaryTitle = IMDB.loc[i,'primaryTitle']
    mode = mapping[IMDB.loc[i,'titleType']]
    pr_desc = IMDB.loc[i,'Description']
    if pr_desc is None:
        try:
            new_desc = getDescription2(primaryTitle,mode)
        except:
            new_desc = None
            exception_lis2.append([i,primaryTitle,IMDB.loc[i,'titleType']])
    else:
        new_desc = None
    desc_lis2.append(new_desc)

the nightmare before christmas
calling the ghosts a story about rape war and women
diva las vegas
the road to el dorado
great minds think 4 themselves
sinister sister
descent freespace the great war
ai artificial intelligence
playboys club lingerie
cyberworld
the making of jaws
interstate 76
mario tennis
mario party 2
mario party 3
m caught in the act
desert lovers
snow falling on cedars spotlight on location
veggietales lyle the kindly viking
freespace 2
blood omen 2
bridgettes hellions
anthony bourdains a cooks tour
debbie does iowa
kannathil muthamittal
area k
kirby 64 the crystal shards
alice in chains the nona tapes
millennium calendar girls
monsters inc the video game
bluer than indigo
dead mans wish
playboys no boys allowed
the terminal
playboys playmates bustin out
sesame street elmos magic cookbook
911 the road to tyranny
kim possible the secret files
kangaroo hitchcock the making of road games
3 am
the rolling stones four flicks 2003
veggietales the star of christmas
penthouse 25th anniversary swimsuit video
all wives party
shrek 2 the video game
veggietales an easter carol
age of empires
an american girl holiday
la femme nikita denise 2
age of empires ii the age of kings
age of mythology
veggietales a snoodles tale
d2
outside the window events in france may 1968
making white nights
final fantasy xi chains of promathia
jak iii
krystal method
veggietales sumo of the opera
it had to be you the great american songbook
undisputed 2 last man standing
of ashes and atoms the story of the nasa plum brook reactor facility
horton hears a who
jerichos echo punk rock in the holy land
inside the party
quackshot starring donald duck
vixens in uniform
an american girl adventure
12 nasty latin girls masturbating 2
the shark is still working the impact legacy of jaws
lost in the thinking
playboys no boys allowed 2
veggietales minnesota cuke and the search for samsons hairbrush
rbi baseball 3
wallace and gromit the curse of the wererabbit on the set part 1
super monkey ball 3d
oz tribute the art of imagination
harolds hollywood on location then now
the call of wild
age of empires iii
spongebob squarepants and friends unite
on the set the lion the witch the wardrobe
fire emblem path of radiance
sesame street whats the name of that song
lost destination lost
spiderman 2
veggietales sheerluck holmes and the golden ruler
the dirt
wolves in the woods
playboys no boys allowed 3 sweet sensations
for you i could die
legend of the end of the century conqueror
we will not be held responsible
an american girl on the home front
the spy who loved me 007 in egypt
goldeneye anatomy of a stunt tank vs perrier
for your eyes only bond in greece
the world is not enough creating an icon making the teaser trailer
goldeneye anatomy of a car chase remy julienne
on her majestys secret service george lazenby in his own words
moonraker ken adams production films
the spy who loved me ken adams production films
you only live twice ken adams production films
goldeneye location scouting with peter lamont
octopussy location scouting with peter lamont
the living daylights timothy dalton on acting
veggietales larryboy and the bad apple
krystal therapy
frog
jennas provocateur
make a wish
lost secrets from the hatch 2006 v
hoop days
confrontation
pursuit
tactics
unraveling
dealings
manda bala send a bullet
overcast
glare
assault
hannah goes to hell
confession
superman doomsday
tomb raider anniversary
spongebob and friends battle for volcano island
green zone
friend
decision
avatar the last airbender the legend of aang
makeshift
performance
guidance
frenzy
validation
silence
renewal
abduction
james burkes connections
impatience
kingdom men rising
the squatchin trilogy
air jaws 2 even higher
father
transfer
boy culture
deti
scorn
selection
the prescription
a chance to love
vigilance
malice
cadence of hyrule
going too far
the legend of zelda tears of the kingdom
i remember ashes
transalpina the road of kings
playboys no boys allowed 4 naughty and nice
snapcubes realtime fandub
the storied life of aj fikry
bad boy bubby being bubby
bad boy bubby christ kid youre a weirdo
saezuru tori wa habatakanai the clouds gather
aew dynamite
spongebob and friends attack of the toybots
the world is not enough the secrets of 007
the world is not enough the boat chase
goldeneye the martin chronicles directing bond segments with martin campbells comments
killer wives
casino royale deleted scenes
thunderball selling bonds original 1965 television commercials
live and let die conceptual art
the dinner parting
no time to die official title reveal of bond 25
behind the scenes with the world is not enough
love inheritance and lunch
mega man star force
another christmas coincidence
the giverny document
square one michael jackson
tron legacy
veggietales special messages
textopia
aew dark
good bye my princess
iliza shlesinger unveiled
seth meyers lobby baby
the peculiar story
tom papa youre doing great
heavens gate the cult of cults
revisioned tomb raider animated series
exhibit a denis leary vs bill hicks
friends the reunion
endgame
vr bangers
mccabe mrs miller way out on a limb
ready
talking tom and friends minis
the mad womens ball
the flower of kim jong ii
a hero in heaven
heineken die another day television commercial
behind the movie no time to die
007 shadows
ze frank
kia pierce brosnan james bond style television commercial
soul nomad the world eaters
faith the unholy trinity
goldeneye 007 video game television commercial
bmw z8 the world is not enough television commercial
geico james bond parody television commercial
rj
bad guys vile city
you knock on my door
michelle buteau welcome to buteaupia
sesame street big bird sings
interrogation of a husband
merman academy the movie
revolt of master ma
detective dee heavenly gods
cult killer the story of rick rodriguez
devils island journey into jungle alcatraz
the windsors a royal dynasty
truman tennessee an intimate conversation
hyrule warriors age of calamity
generosity
karmas world
peerless hero
welcome to los feliz
hush hush sweet charlotte bruce dern remembers
among us logic
nxt takeover wargames iv
the knife of don juan
animal crossing city folk
ayan
mad max fury road introduction to black chrome edition by george miller
dear paul schrader thank you for light sleeper
the dinosaur game
passengers
royal tramp
the search for frida
hamsters and flutes
better you than me
an avemaria with consequences
parking in the snails shell
laugh already
it
the making of never say never again
eagles
monster high
origins
lockdown
the buildup
passovergay
monster pets a hotel transylvania short film
tr
falling angel
spiderman ps4 gameplay with cottrello
the scent of passion
derbez camp
llama llama llama
forward 1
i love montana
3 months later
just for tonight
generation y
olympic highlights with kevin hart snoop dogg
dee renjies burning sky extraordinary fire
sesame street mecha builders
aew rampage
aew all out 2021
the hitmans bodyguard deleted scenes
the hitmans bodyguard extended scenes
the hitmans bodyguard alternate scenes
a christmas carol the video game
one piece strong world
apples oranges lemons limes
the worlds biggest family an anonymous sperm donors legacy
goofy in how to stay at home
blinkytm
sesame street being green
a ruby herring mystery
cowboys gang life 4 ever
werewolf by night
tree climbing lions
an inborn desire
the royal world premiere of no time to die
no time to die anatomy of a scene
bond 25 cnn no time to die special
a soldiers love story
the dragon tomb
rehabilitation from the book of saw
rupauls drag race untucked
the clone
di renjie red eyes
the father
detective dee under the tower
burzynski cancer is serious business
sonic colors
masterchef usa
hero dog 2
act ii purpose
act iii awakening
tales from the lumber yard the making of galaxy of terror
the condemned
memories of a lost love
silver or lead
holbrooktwain an american odyssey
chica
the silent truth
gordon ramsays ultimate christmas
taylor tomlinson look at you
my so has got depression
the blues brothers transposing the music
the blues brothers remembering john
toy story toons hawaiian vacation
invisible empire
a christmas detouring message
a man among wolves
winners
love on the spectrum us
fast furious 6
no time to die designing bond
my heart beats for lola volcn
mont reve short
roxy road
carla
reel black love
aew x njpw forbidden door
snoopy presents to mom and dad with love
tomorrowmen
in space with markiplier part 2
southbound heist
naked swords golden gate
home sweet rome
toy story toons small fry
it was related to me
fishing without nets
super mario 3d land
the delhi show
queenie
passions of the heart
the talisman
pretty perfect
matilda the musical
jo koy live from the los angeles forum
the current war directors cut
gabriel iglesias stadium fluffy
alphabet lore
sesame street imagine that
iliza shlesinger hot forever
fearless heart
habana libre
maddy mays mayhem
top ten
sesame street 123 count with me
return to the uss atlanta
the real anthony fauci
jacques cousteau rediscover the world ii
sesame street sing yourself silly
secret history of hacking
toy story toons partysaurus rex
vena amoris
at all costs
1000 to 1 the cory weissman story
mr rabbit
partners in crime clint eastwood and angelina jolie
trick r treat making friends
the rack pack
the secrets of skyfall
on the art of war
dreams of darkness
bryce
star wars episode viii the last jedi
star wars episode ix the rise of skywalker
childrens theater critic with alfred molina
eastern front
marvel studios building a cinematic universe
sleeping dogs nightmare in north point
two the story of roman nyro
beat beat beat
the old man the gun
the new york philharmonics performance of rodgers hammersteins carousel
the lucky one zac efron becomes a marine
the divine matrix
lego star wars the yoda chronicles
dawn of the head
comissarrio guido brunetti mysteries vendetta
the legend of zelda breath of the wild
radioactive wolves
bravely default flying fairy
chance at romance
start anew world
the walking dead season two
game of bones winter is cumming
sk1
the elder scrolls online
best of enemies buckley vs vidal
invisible spaces
the oscars
mata nui online game
the figures carved into the knife by the sap of the banana trees
wrestlemania 31
kamen rider gaim hyper battle dvd fresh orange arms is born you can also seize it the power of fresh
do you mind
mad god part 2
miracle in the valley
4th man out
mysterious joker
flame
all downhill from here
cobain montage of heck
overwatch
shadowrun dragonfall directors cut
street food around the world
invisible centerfolds
agents of shield double agent
kingdom of tyrants the extended minifilm version
weve met before
sunrise
the groundskeeper
turncoats
a prayer for the lonely
masque
the goal how to version
borderlands going legendary
star wars rebels recon missions
ill find you
steven universe unboxing
fkin actors
dark city introduction by alex proyas and roger ebert
calling in the cavalry
understanding the madness
ultimate iron man
forgotten in california
pillars of eternity the white march part i
clemency
the shape of water
the man with the golden gun american thrill show stunt film
the living daylights the new james bondvienna press conference
bruce lee pursuit of the dragon early version
i hope
electric dreams
love sex tv news
the walking dead a new frontier
the one i lust
the oscars
she loves me
shooting blood simple
my suburban stories
death proof foot spoof
patrick stewart narrates the planets
late night
the butterfly effect
if youre looking for trouble
gustavo goulart it drives me crazy
shamblins shack
teen titans the judas contract
the butler gag reel
mantis nest
the adventures of batman robin
otto frank father of anne
the beep test
the tales of the seven keys
everything gameplay film
idiots
making john adams
do no harm exposing the hippocratic hoax
vixen the movie
all anything or love
quest for the stanley cup
mad god part 3
a gift for christmas
the adventures of priscilla queen of the desert the bus from blooperville
the last wave interview with director peter weir
national treasure kiri
mata hari the naked spy
the knife shaking the habitual live at terminal 5
birth of a monster a star wars story
the art of selfdefense
the submission of emma marx evolved
bloodless
prnom mathieu
the dreaming man
the beguiled a shift in perspective
the beguiled a southern style
american made cruise and liman a conversation
american made flying high
american made the real barry seal
little red riding hood
a river through the mountains
mills creek
the hollow forest chronicles
ibot
kickball team vs church ladies
nubile films
the drug hunter
the hitmans bodyguard dangerous women
the hitmans bodyguard the hitman vs the bodyguard
call me by your name in conversation with armie hammer timothe chalamet michael stuhlbarg and luca guadagnino
a christmas coincidence
constantine city of demons the movie
are you there god its me margaret
threads
pip
the possession of mrs hyde
such sweet sorrow part 2
filming imax under the sea
rifftrax live octaman
anne frank parallel stories
the casebook of sherlock holmes
are you afraid of the dark
xmen the animated series
scent of a woman
carlitos way
schindlers list
the memoirs of sherlock holmes
lon the professional
spiderman the animated series
love letter
se7en
the usual suspects
beast wars transformers
secrets lies
the new batman adventures
in the mood for love
iruvar
la confidential
the truman show
the legend of 1900
xmen
the emperors new groove
detective conan
mahanadi
michael madana kama rajan
u571
the celebration
byomkesh bakshi
mi5
mulholland drive
the sixth sense
arabian nights
traffic
boiler room
me myself irene
a knights tale
yu yu hakusho ghost files
gone in 60 seconds
samsara
love basketball
the way of the gun
rurouni kenshin trust and betrayal
gto great teacher onizuka
clerks
zakhm
amlie
padaiyappa
road trip
vaastav the reality
cardcaptor sakura
kaho naa pyaar hai
the salton sea
oceans eleven
harry potter and the sorcerers stone
alai payuthey
kandukondain kandukondain
lie
the sleeping dictionary
bridget joness diary
and your mother too
kureyon shinchan
anne frank the whole story
tholi prema
for the birds
metal gear solid 2 sons of liberty
kaun banega crorepati
sex and luca
kaalapani
the isle
thenmavin kombath
startupcom
the quiet american
the bourne identity
k19 the widowmaker
adaptation
the last castle
punchdrunk love
the adversary
the hours
lilo stitch
grand theft auto iii
in harihar nagar
father and daughter
mr bean the animated series
no mans land
caesar
monsters ball
degrassi the next generation
the clone
the butterfly effect
tum bin love will find a way
x2 xmen united
the recruit
the rules of attraction
the grim adventures of billy mandy
before the devil knows youre dead
the phantom of the opera
the transporter
rent
the chronicles of riddick
rehnaa hai terre dil mein
lilya 4ever
bad guy
raaz
the dreamers
sympathy for mr vengeance
wallace gromit the curse of the wererabbit
the gathering storm
great teacher onizuka
kadhalukku mariyadhai
pretenders
spiderman 2
the italian job
mission impossible iii
the magdalene sisters
big fish
carnivle
soldiers girl
the last samurai
chobits
the great raid
tremors
full metal panic
dont move
heman and the masters of the universe
the passion of the christ
somethings gotta give
wire in the blood
the polar express
alexandras project
the aviator
a series of unfortunate events
wallace gromits cracking contraptions
azumanga daioh the animation
the station agent
ticker
sex is zero
mangal pandey
chalte chalte
howls moving castle
kal ho naa ho
main hoon na
the door in the floor
oceans twelve
delovely
the life and death of peter sellers
sandesham
the five obstructions
aaram thamburan
mr mrs smith
the ballad of jack and rose
sky kids
easy riders raging bulls how the sex drugs and rock n roll generation saved hollywood
tell no one
the oc
the chronicles of narnia the lion the witch and the wardrobe
metal gear solid 3 snake eater
harold kumar go to white castle
the squid and the whale
the manchurian candidate
im not there
ongbak the thai warrior
reno 911
the hitchhikers guide to the galaxy
the bourne supremacy
power rangers dinothunder
gangaajal
munna bhai mbbs
ayitha ezhuthu
kaakhakaakha the police
goal the dream begins
the lovely bones
310 to yuma
curious george
call of duty
the da vinci code
grand theft auto san andreas
pirates of the caribbean dead mans chest
the weather man
initial d first stage
air crash investigation
the constant gardener
cach hidden
its all gone pete tong
the devils rejects
the skeleton key
corner gas
the baxter
the diving bell and the butterfly
a good year
red vs blue
casanova
the sisterhood of the traveling pants
master i margarita
the exorcism of emily rose
the 40yearold virgin
the great janggeum
ramsays kitchen nightmares
hellboy ii the golden army
the worlds fastest indian
pride prejudice
power rangers spd
mongol the rise of genghis khan
the secret life of bees
the spiderwick chronicles
transformers
jarhead
the kite runner
a prairie home companion
max paddys road to nowhere
the proposition
avrupa yakasi
the valley of the wolves
the curious case of benjamin button
imagine me you
marie antoinette
surfs up
vasoolraja mbbs
fingersmith
darwins nightmare
lila dit a
clerks ii
a moment to remember
ps i love you
fantastic mr fox
the namesake
gantz
keith
gungrave
the devil and daniel johnston
ice age the meltdown
fanaa
the bourne ultimatum
kaamelott
danger close
varalaaru
lincoln
the assassination of jesse james by the coward robert ford
7 days
the wayward cloud
pirates of the caribbean at worlds end
apaharan
no entry
the time travelers wife
sachien
the pursuit of happyness
the crazies
carry on munna bhai
grandmas boy
pans labyrinth
paruthiveeran
xmen origins wolverine
lady chatterley
human trafficking
the simpsons movie
the history boys
sillunu oru kaadhal
the other boleyn girl
the express
9
charlie wilsons war
the batman vs dracula
prince of persia the sands of time
state of play
taxi no 9 2 11 nau do gyarah
starter for 10
extremely loud incredibly close
pastewka
timecrimes
fighting spirit
harold kumar escape from guantanamo bay
the prestige
fuck
the it crowd
welcome
boys over flowers
ashes and snow
halo 3
vivah
oceans thirteen
the chronicles of narnia prince caspian
death note
love other drugs
the baader meinhof complex
samsara
fatestay night
cah cab
summer palace
under the same moon
red dog
its kind of a funny story
lars and the real girl
angels demons
easy virtue
funny games
nana
ouran high school host club
planetes
the melancholy of haruhi suzumiya
a dirty carnival
marley me
forbrydelsen
i cant think straight
definitely maybe
the darjeeling limited
step brothers
the avengers
basilisk the kouga ninja scrolls
welcome to the nhk
battle for terra
vikramarkudu
flight of the conchords
the duchess
mr peabody sherman
the forbidden kingdom
the jane austen book club
lets go india
galactik football
dgrayman
gavin stacey
the boy in the striped pajamas
detective montalbano
malliswari
noroi
200 pounds beauty
ben x
fashion
slam dunk
creation
elegy
jumong
mary and max
nick and norahs infinite playlist
gintama
naruto shippden the movie
code geass
pele birth of a legend
love songs
recount
fittrat
coldd lassi aur chicken masala
medically yourrs
zack and miri make a porno
fast furious
fermats room
les misrables
boris
agent sai srinivasa athreya
hotel del luna
argo
the boarding school
compartment number 6
hachi a dogs tale
the forgotten army azaadi ke liye
poison
illegal justice out of order
unbreakable kimmy schmidt kimmy vs the reverend
hannah gadsby douglas
primal
the descendants
defiance
coda
single slipper size 7
vis a vis el oasis
love life
call of duty modern warfare
arifureta from commonplace to worlds strongest
vratice se rode
yeh saali aashiqui
mission over mars
the other me
given
devil may cry the animated series
the world unseen
lost illusions
ma raineys black bottom
gullak
clarksons farm
life as we know it
the untamed
theory of love
hell is other people
the life ahead
minecraft epic
the burning plain

In [29]:
IMDB['New_Description'] = desc_lis2

In [31]:
IMDB['New_Description'].isnull().sum()

8461

In [32]:
IMDB.isnull().sum() * 100 / len(IMDB)

tconst              0.000000
titleType           0.000000
primaryTitle        0.000000
originalTitle       0.000000
isAdult             0.000000
startYear           0.000000
endYear             0.000000
runtimeMinutes      0.000000
genres              0.000000
averageRating       0.000000
numVotes            0.000000
ordering            0.000000
title               0.000000
region              0.000000
language            0.000000
types               0.000000
attributes          0.000000
isOriginalTitle     0.000000
Description        41.255474
New_Description    82.345499
dtype: float64

In [33]:
dffile4 = open('imdb_desc2','ab')
pickle.dump(IMDB,dffile4)
dffile4.close()

In [34]:
dffile5 = open('imdb_desc2_exceptions','ab')
pickle.dump(exception_lis2,dffile5)
dffile5.close()

## Combining the 2

In [36]:
len(IMDB)

10275

In [35]:
IMDB.head()

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,averageRating,numVotes,ordering,title,region,language,types,attributes,isOriginalTitle,Description,New_Description
0,tt0102926,movie,The Silence of the Lambs,The Silence of the Lambs,0,1991,\N,118,"Crime,Drama,Thriller",8.6,1473918,50,The Silence of the Lambs,US,en,\N,\N,0,"Jodie Foster stars as Clarice Starling, a top ...",None
1,tt0103064,movie,Terminator 2: Judgment Day,Terminator 2: Judgment Day,0,1991,\N,137,"Action,Sci-Fi",8.6,1128166,17,Terminator 2: Judgment Day,US,en,dvd,\N,0,"In this sequel set eleven years after ""The Ter...",None
2,tt0107688,movie,The Nightmare Before Christmas,The Nightmare Before Christmas,0,1993,\N,76,"Animation,Family,Fantasy",7.9,352825,54,The Nightmare Before Christmas,US,en,\N,\N,0,None,None
3,tt0110357,movie,The Lion King,The Lion King,0,1994,\N,88,"Adventure,Animation,Drama",8.5,1090882,18,The Lion King 3D,US,en,\N,3-D version,0,This Disney animated feature follows the adven...,None
4,tt0110912,movie,Pulp Fiction,Pulp Fiction,0,1994,\N,154,"Crime,Drama",8.9,2118762,22,Pulp Fiction,US,en,\N,\N,0,Vincent Vega (John Travolta) and Jules Winnfie...,None

In [37]:
combined_col = []
for i in range(len(IMDB)):
    pr_desc = IMDB.loc[i,'Description']
    new_desc = IMDB.loc[i,'New_Description']
    if pr_desc is not None:
        combined_col.append(pr_desc)
    elif new_desc is not None:
        combined_col.append(new_desc)
    else:
        combined_col.append(None)

In [52]:
IMDB['Comb_Description'] = combined_col

In [53]:
IMDB['Comb_Description'].isnull().sum()

2425

In [61]:
IMDB.isnull().sum() * 100 / len(IMDB)

tconst              0.000000
titleType           0.000000
primaryTitle        0.000000
originalTitle       0.000000
isAdult             0.000000
startYear           0.000000
endYear             0.000000
runtimeMinutes      0.000000
genres              0.000000
averageRating       0.000000
numVotes            0.000000
ordering            0.000000
title               0.000000
region              0.000000
language            0.000000
types               0.000000
attributes          0.000000
isOriginalTitle     0.000000
Description        23.600973
dtype: float64

In [60]:
IMDB.head()

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,averageRating,numVotes,ordering,title,region,language,types,attributes,isOriginalTitle,Description
0,tt0102926,movie,The Silence of the Lambs,The Silence of the Lambs,0,1991,\N,118,"Crime,Drama,Thriller",8.6,1473918,50,The Silence of the Lambs,US,en,\N,\N,0,"Jodie Foster stars as Clarice Starling, a top ..."
1,tt0103064,movie,Terminator 2: Judgment Day,Terminator 2: Judgment Day,0,1991,\N,137,"Action,Sci-Fi",8.6,1128166,17,Terminator 2: Judgment Day,US,en,dvd,\N,0,"In this sequel set eleven years after ""The Ter..."
2,tt0107688,movie,The Nightmare Before Christmas,The Nightmare Before Christmas,0,1993,\N,76,"Animation,Family,Fantasy",7.9,352825,54,The Nightmare Before Christmas,US,en,\N,\N,0,None
3,tt0110357,movie,The Lion King,The Lion King,0,1994,\N,88,"Adventure,Animation,Drama",8.5,1090882,18,The Lion King 3D,US,en,\N,3-D version,0,This Disney animated feature follows the adven...
4,tt0110912,movie,Pulp Fiction,Pulp Fiction,0,1994,\N,154,"Crime,Drama",8.9,2118762,22,Pulp Fiction,US,en,\N,\N,0,Vincent Vega (John Travolta) and Jules Winnfie...

In [55]:
IMDB.drop(['Description', 'New_Description'], axis=1,inplace=True)

In [56]:
IMDB.rename(columns = {'Comb_Description':'Description'}, inplace = True)

In [59]:
dffile6 = open('imdb_desc2','ab')
pickle.dump(IMDB,dffile6)
dffile6.close()

In [62]:
IMDB_not_null = IMDB.dropna(subset=['Description'])
IMDB_not_null.reset_index(inplace=True)

In [17]:
data_path = os.path.join(dirname(dirname(os.getcwd())),'data')
imdb_filt_path = os.path.join(data_path,'imdb_filtered')
IMDB_not_null.to_csv(os.path.join(imdb_filt_path,'IMDB.csv'))

In [19]:
IMDB_not_null.columns

Index(['index', 'tconst', 'titleType', 'primaryTitle', 'originalTitle',
       'isAdult', 'startYear', 'endYear', 'runtimeMinutes', 'genres',
       'averageRating', 'numVotes', 'ordering', 'title', 'region', 'language',
       'types', 'attributes', 'isOriginalTitle', 'Description'],
      dtype='object')

# Start here 4

In [ ]:
# dffile4 = open('imdb_desc2','rb')
# IMDB = pickle.load(dffile4)
# dffile4.close()

# Assumptions or Filters
* Only Canada, Greater Britain, India, and USA currently
* Only movies/shows from 1990s onwards
* movies/shows from the 90s aare greater than 7.9 and above 
* movies/shows from the 2000s and onwards are 6.5 aand above 
* Greater than 3000 no. of votes for Cananda and India
* Might've removed extra season stuff (Check series and seasons if they're intact)

# Problems to Fix
* While removing duplicates by region I kept the first random country, so there's a possibility that Game of thrones may be under India indtead of Greater Britain
* I didn't incorporate '& -> and' and other contractions for extraacting descriptions


# Ideas to remember
* Search bar autocomplete (validates if in database also)
* Disclaimer of assumptions in UI
* Add filters such as country, language, tv/movie
* Have option of recommending both ways
* Something so the user can ask, movies based on New york (Key words in description filtering)
    * See if i can add a kids / disney filter or key word or genre or something
    * Maybe use stopwords that only let nouns remain or something
* To make it more presentable use movie posters or something from some API
* Maybe tell the users on what basis the recommendation has been made
* Check if we have a reality genre (great british beaking show)
* Tell the users which language the movie is in by detecting the title language or something
* Take multiple movie or book inputs
* Once input taken tell the user that "I guess this aspect is what you like in all of these __" - so basically finding similarity too
* If book recommended is because its based on that book  then expliccitly mention it and also make sure it is recommended (not forcefully though)
* provide link to goodreads list